name: Project May 12 CI

on:
  push:
    branches: 
        - work21may

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build Docker image
              run: docker build -t project-may12 .

            - name: Run container
              run: |
                docker run -d -p 8000:4500 --name project_may12_container project_may12

            - name: Wait for app to be ready
              run: sleep 50

            - name: Test API
              run: |
                curl -X POST http://localhost:8000/ask \
                -H "Content-Type: application/json" \
                -d '{"question": "What is the capital of France?"}'

            - name: Cleanup
              run: |
                docker stop project_may12_container
                docker rm project_may12_container